server:
  port: 8080

spring:
  application:
    name: loandly

  #Kakao Oauth2 로그인 정보
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test-client-id
            client-secret: test-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  #h2
  datasource:
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  #jpa
  jpa:
    hibernate:
      ddl-auto: create-drop    # create, update, none 등
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  #redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  cache:
    type: none

#Log
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.client.endpoint: DEBUG
