name: Run Tests

# main과 develop의 PR시 테스트
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    # 어떤 OS 를 사용하여 돌릴 것인지
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    #코드를 Runner 환경으로 가져와야 함
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 어떤 JDK를 사용할지 -> 프로젝트와 맞춰줘야 함
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Debug Redis container
        run: |
          echo "== docker ps =="
          docker ps -a

          echo "== redis logs =="
          docker logs $(docker ps -q --filter ancestor=redis) || true

          echo "== netcat test =="
          nc -zv localhost 6379 || echo "Redis not reachable"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test --stacktrace

#CD 스크립트 추후 작성 예정
