name: Create PR main → develop

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR from main to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: develop
          branch: sync-main-to-develop-automated
          title: "자동화: main → develop 최신화 PR"
          body: |
            main 브랜치 업데이트로 인한 develop 최신화를 위한 자동 PR입니다.
