name: Sync main to develop

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR from develop to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: develop
          destination_branch: main
          pr_title: "자동화: develop → main PR"
          pr_body: |
            develop 브랜치에서 main 브랜치로의 자동 PR입니다.
          github_token: ${{ secrets.GITHUB_TOKEN }}
